### ISSUE TITLE
CI, "combine the following with that file in the right way!" and Gitbuilding

### ISSUE THREAD

**Issue by jcolomb** [hoijui/osh-tool#44]
hello,

I have a repo using gitbuilding CI, it would be good to have an explanation on how to combine the two CI elements, I think I could understand what the "right way" is from an example (?).

Note:
gitbuilding.yml:
```
name: Deploy Gitbuilding Project to Github Pages

on: [push]

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Build
        run: |
          pip install gitbuilding
          gitbuilding build-html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _site/
          # Automatically remove deleted files from the deploy branch
          CLEAN: true

```
